//! Module for Flow related types
use std::{
    any::{Any, type_name},
    collections::{HashMap, VecDeque},
    sync::{
        Arc,
        atomic::{AtomicU32, Ordering},
    },
};

use anyhow::Result;
use dyn_clone::DynClone;
use serde::{Deserialize, Serialize};
use slotmap::{SecondaryMap, SlotMap, new_key_type};

use crate::{
    engine::{EngineError, SlotIndex, bbp::PoolExecutor, tick::Tick},
    model::{DataKind, project::ProjectData},
};

pub mod nodes;

new_key_type! {
    pub struct NodeID;
    pub struct SocketID;
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum SocketDirection {
    Input,
    Output,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SocketMeta {
    pub owner: NodeID,
    pub direction: SocketDirection,
    pub kind: DataKind,
    pub name: String,
    pub visible: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Socket {
    pub kind: DataKind,
    pub name: String,
    pub visible: bool,
}

impl Socket {
    pub fn new(kind: DataKind, name: impl Into<String>, visible: bool) -> Self {
        Self {
            kind,
            name: name.into(),
            visible,
        }
    }
}

impl SocketMeta {
    pub fn new(
        owner: NodeID,
        direction: SocketDirection,
        name: impl Into<String>,
        kind: DataKind,
        visible: bool,
    ) -> SocketMeta {
        Self {
            owner,
            direction,
            kind,
            name: name.into(),
            visible,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Param(Arc<AtomicU32>); // f32 via to_bits/from_bits

impl Param {
    pub fn new(v: f32) -> Self {
        Self(Arc::new(AtomicU32::new(v.to_bits())))
    }
    #[inline]
    pub fn get(&self) -> f32 {
        f32::from_bits(self.0.load(Ordering::Relaxed))
    }
    #[inline]
    pub fn set(&self, v: f32) {
        self.0.store(v.to_bits(), Ordering::Relaxed);
    }
}

pub trait Node: std::fmt::Debug + DynClone + Send + Sync + 'static {
    type State: Send + 'static;

    fn spec_in(&self) -> Vec<Socket>;
    fn spec_out(&self) -> Vec<Socket>;

    /// Fresh runtime state for a new instance of this node, built off the
    /// audio thread (control thread, inside `publish_current`) and handed
    /// over pre-built.
    fn init_state(&self) -> Self::State;

    fn process(
        &self,
        pool: &mut PoolExecutor,
        state: &mut Self::State,
        project: &ProjectData,
        block_start: Tick,
        inputs: &[SlotIndex],
        outputs: &[SlotIndex],
    );

    fn grow_input(&mut self) -> anyhow::Result<Socket> {
        anyhow::bail!("Tried growing input arity on a fixed-arity node")
    }
    fn shrink_input(&mut self, socket: SocketID) -> bool {
        false
    } // true = safe to actually remove
}

pub trait MultiInputNode: ErasedNode {}

pub trait ErasedNode: std::fmt::Debug + DynClone + Send + Sync + 'static {
    fn spec_in(&self) -> Vec<Socket>;
    fn spec_out(&self) -> Vec<Socket>;
    fn spawn_state(&self) -> Box<dyn Any + Send>;
    fn process_erased(
        &self,
        pool: &mut PoolExecutor,
        state: &mut dyn Any,
        project: &ProjectData,
        block_start: Tick,
        inputs: &[SlotIndex],
        outputs: &[SlotIndex],
    );
    fn as_any_mut(&mut self) -> &mut dyn Any;
}

dyn_clone::clone_trait_object!(ErasedNode);

impl<N: Node> ErasedNode for N {
    fn spec_in(&self) -> Vec<Socket> {
        Node::spec_in(self)
    }

    fn spec_out(&self) -> Vec<Socket> {
        Node::spec_out(self)
    }

    fn spawn_state(&self) -> Box<dyn Any + Send> {
        Box::new(self.init_state())
    }

    fn process_erased(
        &self,
        pool: &mut PoolExecutor,
        state: &mut dyn Any,
        project: &ProjectData,
        block_start: Tick,
        inputs: &[SlotIndex],
        outputs: &[SlotIndex],
    ) {
        let state = state.downcast_mut::<N::State>()
        .expect(&format!("type mismatch impossible: this pairing is generated by the blanket impl, never hand-written\n Expected: {}", type_name::<N::State>()));
        self.process(pool, state, project, block_start, inputs, outputs);
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct Link {
    pub from: SocketID,
    pub to: SocketID,
}

/// A graph representing the signal flow between nodes.
#[derive(Debug, Default, Clone)]
pub struct NodeGraph {
    pub nodes: SlotMap<NodeID, Box<dyn ErasedNode>>,
    pub sockets: SlotMap<SocketID, SocketMeta>,
    pub node_sockets: SecondaryMap<NodeID, (Vec<SocketID>, Vec<SocketID>)>, // ordered inputs, outputs
    // pub links: HashSet<Link>,

    // Map Incoming -> Outgoing sockets
    // essentially, maps sockets to where they get their value from
    pub links: HashMap<SocketID, SocketID>,
}

impl NodeGraph {
    pub fn inputs_of(&self, node: NodeID) -> &[SocketID] {
        self.node_sockets.get(node).map_or(&[], |(ins, _)| ins)
    }
    pub fn outputs_of(&self, node: NodeID) -> &[SocketID] {
        self.node_sockets.get(node).map_or(&[], |(_, outs)| outs)
    }

    /// Robust against future reordering/insertion in a node's shape — looks
    /// up by the stable name in SocketMeta rather than position.
    pub fn socket_named(&self, node: NodeID, dir: SocketDirection, name: &str) -> Option<SocketID> {
        let (ins, outs) = self.node_sockets.get(node)?;
        let candidates = match dir {
            SocketDirection::Input => ins,
            SocketDirection::Output => outs,
        };
        candidates
            .iter()
            .copied()
            .find(|&id| self.sockets[id].name == name)
    }

    pub fn purge(&mut self, node_id: NodeID) {
        self.nodes.remove(node_id);
        if let Some((in_sockets, out_sockets)) = self.node_sockets.remove(node_id) {
            for socket in in_sockets.iter().chain(out_sockets.iter()) {
                self.sockets.remove(*socket).unwrap();
            }
        }
    }

    pub fn remove_link(&mut self, from: SocketID, to: SocketID) -> Result<()> {
        self.links
            .retain(|l_dest, l_source| !(*l_source == from && *l_dest == to));
        Ok(())
    }

    pub fn add_node<N: Node>(&mut self, node: N) -> NodeID {
        let (inputs, outputs) = (node.spec_in(), node.spec_out());
        let node_id = self.nodes.insert(Box::new(node));
        let register =
            |graph: &mut NodeGraph, socks: Vec<Socket>, dir: SocketDirection| -> Vec<SocketID> {
                socks
                    .into_iter()
                    .map(|s| {
                        graph.sockets.insert(SocketMeta {
                            owner: node_id,
                            direction: dir,
                            kind: s.kind,
                            name: s.name,
                            visible: s.visible,
                        })
                    })
                    .collect()
            };
        let input_ids = register(self, inputs, SocketDirection::Input);
        let output_ids = register(self, outputs, SocketDirection::Output);
        self.node_sockets.insert(node_id, (input_ids, output_ids));
        node_id
    }

    pub fn add_link(&mut self, from_id: SocketID, to_id: SocketID) -> Result<Option<SocketID>> {
        let from = &self.sockets[from_id];
        let to = &self.sockets[to_id];

        if from.direction != SocketDirection::Output || to.direction != SocketDirection::Input {
            anyhow::bail!(
                "Socket connection must be I->O, found {:?} -> {:?}",
                from.direction,
                to.direction
            );
        }

        if !from.kind.can_connect_to(to.kind) {
            anyhow::bail!("Invalid connection: {:?} -> {:?}", from.kind, to.kind)
        }

        let prev_link = self.links.insert(from_id, to_id);

        if self.topo_sort().is_err() {
            self.remove_link(from_id, to_id);
            return Err(EngineError::WouldCreateCycle.into());
        }
        Ok(prev_link)
    }

    /// Kahn's algorithm topological sort + a bump-allocated buffer slot per
    /// output socket. No slot reuse yet (see the buffer-pooling discussion —
    /// this is the register-allocation pass that'd go here later); today's
    /// graphs are tiny so it doesn't matter yet.
    /// Kahn's algorithm, shared by compile_graph (which needs the order) and
    /// link validation (which only needs to know whether an order exists).
    pub fn topo_sort(&self) -> Result<Vec<NodeID>> {
        let mut in_degree: HashMap<NodeID, usize> = self.nodes.keys().map(|id| (id, 0)).collect();

        for (to, from) in self.links.iter() {
            let to_node = self.sockets[*to].owner;
            let from_node = self.sockets[*from].owner;
            *in_degree
                .get_mut(&to_node)
                .ok_or(EngineError::NodeNotFound(to_node))? += 1;
        }

        let mut remaining = in_degree.clone();
        let mut queue: VecDeque<NodeID> = in_degree
            .iter()
            .filter(|(_, d)| **d == 0)
            .map(|(&id, _)| id)
            .collect();
        let mut order = Vec::with_capacity(self.nodes.len());

        while let Some(n) = queue.pop_front() {
            order.push(n);
            for (to, from) in self.links.iter().filter(|(_, from)| {
                let from_node = self.sockets[**from].owner;
                from_node == n
            }) {
                let to_node = self.sockets[*to].owner;
                let d = remaining.get_mut(&to_node).unwrap();
                *d -= 1;
                if *d == 0 {
                    queue.push_back(to_node);
                }
            }
        }
        if order.len() != self.nodes.len() {
            return Err(EngineError::WouldCreateCycle.into());
        }
        Ok(order)
    }
}
