//! Module for Flow related types
use std::{
    any::{Any, type_name},
    sync::{
        Arc,
        atomic::{AtomicU32, Ordering},
    },
};

use dyn_clone::DynClone;
use serde::{Deserialize, Serialize};
use slotmap::{SlotMap, new_key_type};

use crate::{
    engine::{SlotIndex, bbp::PoolExecutor, tick::Tick},
    model::{DataKind, Kind, project::ProjectData},
};

pub mod nodes;

new_key_type! {
    pub struct NodeID;
    pub struct LinkID;
}

pub type SocketIndex = usize;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Socket {
    pub kind: DataKind,
    pub name: &'static str,
    pub visible: bool,
}

impl Socket {
    pub fn new<C: Kind>(name: impl Into<String>, visible: bool) -> Socket {
        Self {
            kind: C::into_datakind(),
            name: name.into().leak(),
            visible,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Param(Arc<AtomicU32>); // f32 via to_bits/from_bits

impl Param {
    pub fn new(v: f32) -> Self {
        Self(Arc::new(AtomicU32::new(v.to_bits())))
    }
    #[inline]
    pub fn get(&self) -> f32 {
        f32::from_bits(self.0.load(Ordering::Relaxed))
    }
    #[inline]
    pub fn set(&self, v: f32) {
        self.0.store(v.to_bits(), Ordering::Relaxed);
    }
}

pub trait Node: std::fmt::Debug + DynClone + Send + Sync + 'static {
    type State: Send + 'static;

    fn inputs(&self) -> &[Socket];
    fn outputs(&self) -> &[Socket];

    /// Fresh runtime state for a new instance of this node, built off the
    /// audio thread (control thread, inside `publish_current`) and handed
    /// over pre-built. Nodes with no runtime state (Master, TrackReader)
    /// use the default.
    fn init_state(&self) -> Self::State;

    fn process(
        &self,
        state: &mut Self::State,
        project: &ProjectData,
        pool: &mut PoolExecutor,
        block_start: Tick,
        inputs: &[SlotIndex],
        outputs: &[SlotIndex],
    );
}

pub trait ErasedNode: std::fmt::Debug + DynClone + Send + Sync + 'static {
    fn inputs(&self) -> &[Socket];
    fn outputs(&self) -> &[Socket];
    fn spawn_state(&self) -> Box<dyn Any + Send>;
    fn process_erased(
        &self,
        state: &mut dyn Any,
        project: &ProjectData,
        pool: &mut PoolExecutor,
        block_start: Tick,
        inputs: &[SlotIndex],
        outputs: &[SlotIndex],
    );
}
dyn_clone::clone_trait_object!(ErasedNode);

impl<N: Node> ErasedNode for N {
    fn inputs(&self) -> &[Socket] {
        Node::inputs(self)
    }
    fn outputs(&self) -> &[Socket] {
        Node::outputs(self)
    }
    fn spawn_state(&self) -> Box<dyn Any + Send> {
        Box::new(self.init_state())
    }

    fn process_erased(
        &self,
        state: &mut dyn Any,
        project: &ProjectData,
        pool: &mut PoolExecutor,
        block_start: Tick,
        inputs: &[SlotIndex],
        outputs: &[SlotIndex],
    ) {
        let state = state.downcast_mut::<N::State>()
        .expect(&format!("type mismatch impossible: this pairing is generated by the blanket impl, never hand-written\n Expected: {}", type_name::<N::State>()));
        self.process(state, project, pool, block_start, inputs, outputs);
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Link {
    pub from: (NodeID, SocketIndex),
    pub to: (NodeID, SocketIndex),
}

/// A graph representing the signal flow between nodes.
#[derive(Debug, Default, Clone)]
pub struct NodeGraph {
    pub nodes: SlotMap<NodeID, Box<dyn ErasedNode>>,
    pub links: SlotMap<LinkID, Link>,
}
